// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/chat_controller.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AttachmentPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ChangesPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ChatControllerPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Changes
  dco_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    dynamic raw,
  );

  @protected
  Attachment
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    dynamic raw,
  );

  @protected
  Changes
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    dynamic raw,
  );

  @protected
  ChatController
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    dynamic raw,
  );

  @protected
  Changes
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    dynamic raw,
  );

  @protected
  ChatController
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    dynamic raw,
  );

  @protected
  Changes
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    dynamic raw,
  );

  @protected
  ChatController
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    dynamic raw,
  );

  @protected
  Attachment
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    dynamic raw,
  );

  @protected
  Changes
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    dynamic raw,
  );

  @protected
  ChatController
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    dynamic raw,
  );

  @protected
  RustStreamSink<StateChange> dco_decode_StreamSink_state_change_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ChangesId dco_decode_box_autoadd_changes_id(dynamic raw);

  @protected
  EventLocation dco_decode_box_autoadd_event_location(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  Me dco_decode_box_autoadd_me(dynamic raw);

  @protected
  StateChange dco_decode_box_autoadd_state_change(dynamic raw);

  @protected
  ChangesId dco_decode_changes_id(dynamic raw);

  @protected
  Chat dco_decode_chat(dynamic raw);

  @protected
  ChatError dco_decode_chat_error(dynamic raw);

  @protected
  Event dco_decode_event(dynamic raw);

  @protected
  EventLocation dco_decode_event_location(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Group dco_decode_group(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<Attachment>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Group> dco_decode_list_group(dynamic raw);

  @protected
  List<PollOption> dco_decode_list_poll_option(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Reaction> dco_decode_list_reaction(dynamic raw);

  @protected
  List<(Uint8List?, String)>
  dco_decode_list_record_opt_list_prim_u_8_strict_string(dynamic raw);

  @protected
  Me dco_decode_me(dynamic raw);

  @protected
  MeDeltaState dco_decode_me_delta_state(dynamic raw);

  @protected
  Member dco_decode_member(dynamic raw);

  @protected
  Message dco_decode_message(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  EventLocation? dco_decode_opt_box_autoadd_event_location(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  List<Attachment>?
  dco_decode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    dynamic raw,
  );

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(Uint8List?, String)>?
  dco_decode_opt_list_record_opt_list_prim_u_8_strict_string(dynamic raw);

  @protected
  Poll dco_decode_poll(dynamic raw);

  @protected
  PollOption dco_decode_poll_option(dynamic raw);

  @protected
  Reaction dco_decode_reaction(dynamic raw);

  @protected
  (Uint8List?, String) dco_decode_record_opt_list_prim_u_8_strict_string(
    dynamic raw,
  );

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  StateChange dco_decode_state_change(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  User dco_decode_user(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Visibility dco_decode_visibility(dynamic raw);

  @protected
  VotingType dco_decode_voting_type(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Changes
  sse_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    SseDeserializer deserializer,
  );

  @protected
  Attachment
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    SseDeserializer deserializer,
  );

  @protected
  Changes
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    SseDeserializer deserializer,
  );

  @protected
  ChatController
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    SseDeserializer deserializer,
  );

  @protected
  Changes
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    SseDeserializer deserializer,
  );

  @protected
  ChatController
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    SseDeserializer deserializer,
  );

  @protected
  Changes
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    SseDeserializer deserializer,
  );

  @protected
  ChatController
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    SseDeserializer deserializer,
  );

  @protected
  Attachment
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    SseDeserializer deserializer,
  );

  @protected
  Changes
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    SseDeserializer deserializer,
  );

  @protected
  ChatController
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<StateChange> sse_decode_StreamSink_state_change_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ChangesId sse_decode_box_autoadd_changes_id(SseDeserializer deserializer);

  @protected
  EventLocation sse_decode_box_autoadd_event_location(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Me sse_decode_box_autoadd_me(SseDeserializer deserializer);

  @protected
  StateChange sse_decode_box_autoadd_state_change(SseDeserializer deserializer);

  @protected
  ChangesId sse_decode_changes_id(SseDeserializer deserializer);

  @protected
  Chat sse_decode_chat(SseDeserializer deserializer);

  @protected
  ChatError sse_decode_chat_error(SseDeserializer deserializer);

  @protected
  Event sse_decode_event(SseDeserializer deserializer);

  @protected
  EventLocation sse_decode_event_location(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Group sse_decode_group(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<Attachment>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Group> sse_decode_list_group(SseDeserializer deserializer);

  @protected
  List<PollOption> sse_decode_list_poll_option(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Reaction> sse_decode_list_reaction(SseDeserializer deserializer);

  @protected
  List<(Uint8List?, String)>
  sse_decode_list_record_opt_list_prim_u_8_strict_string(
    SseDeserializer deserializer,
  );

  @protected
  Me sse_decode_me(SseDeserializer deserializer);

  @protected
  MeDeltaState sse_decode_me_delta_state(SseDeserializer deserializer);

  @protected
  Member sse_decode_member(SseDeserializer deserializer);

  @protected
  Message sse_decode_message(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  EventLocation? sse_decode_opt_box_autoadd_event_location(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  List<Attachment>?
  sse_decode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(Uint8List?, String)>?
  sse_decode_opt_list_record_opt_list_prim_u_8_strict_string(
    SseDeserializer deserializer,
  );

  @protected
  Poll sse_decode_poll(SseDeserializer deserializer);

  @protected
  PollOption sse_decode_poll_option(SseDeserializer deserializer);

  @protected
  Reaction sse_decode_reaction(SseDeserializer deserializer);

  @protected
  (Uint8List?, String) sse_decode_record_opt_list_prim_u_8_strict_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  StateChange sse_decode_state_change(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  User sse_decode_user(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Visibility sse_decode_visibility(SseDeserializer deserializer);

  @protected
  VotingType sse_decode_voting_type(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    Changes self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    Attachment self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    Changes self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    ChatController self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    Changes self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    ChatController self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    Changes self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    ChatController self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    Attachment self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    Changes self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    ChatController self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_state_change_Sse(
    RustStreamSink<StateChange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_changes_id(
    ChangesId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_event_location(
    EventLocation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_me(Me self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_state_change(
    StateChange self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_changes_id(ChangesId self, SseSerializer serializer);

  @protected
  void sse_encode_chat(Chat self, SseSerializer serializer);

  @protected
  void sse_encode_chat_error(ChatError self, SseSerializer serializer);

  @protected
  void sse_encode_event(Event self, SseSerializer serializer);

  @protected
  void sse_encode_event_location(EventLocation self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_group(Group self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    List<Attachment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_group(List<Group> self, SseSerializer serializer);

  @protected
  void sse_encode_list_poll_option(
    List<PollOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reaction(List<Reaction> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_opt_list_prim_u_8_strict_string(
    List<(Uint8List?, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_me(Me self, SseSerializer serializer);

  @protected
  void sse_encode_me_delta_state(MeDeltaState self, SseSerializer serializer);

  @protected
  void sse_encode_member(Member self, SseSerializer serializer);

  @protected
  void sse_encode_message(Message self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_event_location(
    EventLocation? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    List<Attachment>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_record_opt_list_prim_u_8_strict_string(
    List<(Uint8List?, String)>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_poll(Poll self, SseSerializer serializer);

  @protected
  void sse_encode_poll_option(PollOption self, SseSerializer serializer);

  @protected
  void sse_encode_reaction(Reaction self, SseSerializer serializer);

  @protected
  void sse_encode_record_opt_list_prim_u_8_strict_string(
    (Uint8List?, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_state_change(StateChange self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user(User self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_visibility(Visibility self, SseSerializer serializer);

  @protected
  void sse_encode_voting_type(VotingType self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChanges(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerChatController(
    int ptr,
  );
}
