// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/chat_api.dart';
import 'api/database.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ApiPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AttachmentPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_DbPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbPtr;

  @protected
  Api
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    dynamic raw,
  );

  @protected
  Attachment
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    dynamic raw,
  );

  @protected
  Db
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb(
    dynamic raw,
  );

  @protected
  Api
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    dynamic raw,
  );

  @protected
  Db
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb(
    dynamic raw,
  );

  @protected
  Api
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    dynamic raw,
  );

  @protected
  Attachment
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    dynamic raw,
  );

  @protected
  Db
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Event dco_decode_box_autoadd_event(dynamic raw);

  @protected
  EventLocation dco_decode_box_autoadd_event_location(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  Me dco_decode_box_autoadd_me(dynamic raw);

  @protected
  Message dco_decode_box_autoadd_message(dynamic raw);

  @protected
  Poll dco_decode_box_autoadd_poll(dynamic raw);

  @protected
  User dco_decode_box_autoadd_user(dynamic raw);

  @protected
  Chat dco_decode_chat(dynamic raw);

  @protected
  ChatError dco_decode_chat_error(dynamic raw);

  @protected
  Event dco_decode_event(dynamic raw);

  @protected
  EventLocation dco_decode_event_location(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Group dco_decode_group(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<Attachment>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Chat> dco_decode_list_chat(dynamic raw);

  @protected
  List<Event> dco_decode_list_event(dynamic raw);

  @protected
  List<Group> dco_decode_list_group(dynamic raw);

  @protected
  List<Member> dco_decode_list_member(dynamic raw);

  @protected
  List<Message> dco_decode_list_message(dynamic raw);

  @protected
  List<Poll> dco_decode_list_poll(dynamic raw);

  @protected
  List<PollOption> dco_decode_list_poll_option(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Reaction> dco_decode_list_reaction(dynamic raw);

  @protected
  List<User> dco_decode_list_user(dynamic raw);

  @protected
  Me dco_decode_me(dynamic raw);

  @protected
  Member dco_decode_member(dynamic raw);

  @protected
  Message dco_decode_message(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  EventLocation? dco_decode_opt_box_autoadd_event_location(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  Me? dco_decode_opt_box_autoadd_me(dynamic raw);

  @protected
  User? dco_decode_opt_box_autoadd_user(dynamic raw);

  @protected
  List<Attachment>?
  dco_decode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    dynamic raw,
  );

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  Poll dco_decode_poll(dynamic raw);

  @protected
  PollOption dco_decode_poll_option(dynamic raw);

  @protected
  Reaction dco_decode_reaction(dynamic raw);

  @protected
  (Event, Message) dco_decode_record_event_message(dynamic raw);

  @protected
  (Poll, Message) dco_decode_record_poll_message(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  User dco_decode_user(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Visibility dco_decode_visibility(dynamic raw);

  @protected
  VotingType dco_decode_voting_type(dynamic raw);

  @protected
  Api
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    SseDeserializer deserializer,
  );

  @protected
  Attachment
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    SseDeserializer deserializer,
  );

  @protected
  Db
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb(
    SseDeserializer deserializer,
  );

  @protected
  Api
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    SseDeserializer deserializer,
  );

  @protected
  Db
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb(
    SseDeserializer deserializer,
  );

  @protected
  Api
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    SseDeserializer deserializer,
  );

  @protected
  Attachment
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    SseDeserializer deserializer,
  );

  @protected
  Db
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Event sse_decode_box_autoadd_event(SseDeserializer deserializer);

  @protected
  EventLocation sse_decode_box_autoadd_event_location(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Me sse_decode_box_autoadd_me(SseDeserializer deserializer);

  @protected
  Message sse_decode_box_autoadd_message(SseDeserializer deserializer);

  @protected
  Poll sse_decode_box_autoadd_poll(SseDeserializer deserializer);

  @protected
  User sse_decode_box_autoadd_user(SseDeserializer deserializer);

  @protected
  Chat sse_decode_chat(SseDeserializer deserializer);

  @protected
  ChatError sse_decode_chat_error(SseDeserializer deserializer);

  @protected
  Event sse_decode_event(SseDeserializer deserializer);

  @protected
  EventLocation sse_decode_event_location(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Group sse_decode_group(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<Attachment>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Chat> sse_decode_list_chat(SseDeserializer deserializer);

  @protected
  List<Event> sse_decode_list_event(SseDeserializer deserializer);

  @protected
  List<Group> sse_decode_list_group(SseDeserializer deserializer);

  @protected
  List<Member> sse_decode_list_member(SseDeserializer deserializer);

  @protected
  List<Message> sse_decode_list_message(SseDeserializer deserializer);

  @protected
  List<Poll> sse_decode_list_poll(SseDeserializer deserializer);

  @protected
  List<PollOption> sse_decode_list_poll_option(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Reaction> sse_decode_list_reaction(SseDeserializer deserializer);

  @protected
  List<User> sse_decode_list_user(SseDeserializer deserializer);

  @protected
  Me sse_decode_me(SseDeserializer deserializer);

  @protected
  Member sse_decode_member(SseDeserializer deserializer);

  @protected
  Message sse_decode_message(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  EventLocation? sse_decode_opt_box_autoadd_event_location(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Me? sse_decode_opt_box_autoadd_me(SseDeserializer deserializer);

  @protected
  User? sse_decode_opt_box_autoadd_user(SseDeserializer deserializer);

  @protected
  List<Attachment>?
  sse_decode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  Poll sse_decode_poll(SseDeserializer deserializer);

  @protected
  PollOption sse_decode_poll_option(SseDeserializer deserializer);

  @protected
  Reaction sse_decode_reaction(SseDeserializer deserializer);

  @protected
  (Event, Message) sse_decode_record_event_message(
    SseDeserializer deserializer,
  );

  @protected
  (Poll, Message) sse_decode_record_poll_message(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  User sse_decode_user(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Visibility sse_decode_visibility(SseDeserializer deserializer);

  @protected
  VotingType sse_decode_voting_type(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    Api self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    Attachment self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb(
    Db self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    Api self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb(
    Db self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    Api self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    Attachment self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb(
    Db self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_event(Event self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_event_location(
    EventLocation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_me(Me self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_message(Message self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_poll(Poll self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user(User self, SseSerializer serializer);

  @protected
  void sse_encode_chat(Chat self, SseSerializer serializer);

  @protected
  void sse_encode_chat_error(ChatError self, SseSerializer serializer);

  @protected
  void sse_encode_event(Event self, SseSerializer serializer);

  @protected
  void sse_encode_event_location(EventLocation self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_group(Group self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    List<Attachment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chat(List<Chat> self, SseSerializer serializer);

  @protected
  void sse_encode_list_event(List<Event> self, SseSerializer serializer);

  @protected
  void sse_encode_list_group(List<Group> self, SseSerializer serializer);

  @protected
  void sse_encode_list_member(List<Member> self, SseSerializer serializer);

  @protected
  void sse_encode_list_message(List<Message> self, SseSerializer serializer);

  @protected
  void sse_encode_list_poll(List<Poll> self, SseSerializer serializer);

  @protected
  void sse_encode_list_poll_option(
    List<PollOption> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reaction(List<Reaction> self, SseSerializer serializer);

  @protected
  void sse_encode_list_user(List<User> self, SseSerializer serializer);

  @protected
  void sse_encode_me(Me self, SseSerializer serializer);

  @protected
  void sse_encode_member(Member self, SseSerializer serializer);

  @protected
  void sse_encode_message(Message self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_event_location(
    EventLocation? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_me(Me? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_user(User? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    List<Attachment>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_poll(Poll self, SseSerializer serializer);

  @protected
  void sse_encode_poll_option(PollOption self, SseSerializer serializer);

  @protected
  void sse_encode_reaction(Reaction self, SseSerializer serializer);

  @protected
  void sse_encode_record_event_message(
    (Event, Message) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_poll_message(
    (Poll, Message) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user(User self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_visibility(Visibility self, SseSerializer serializer);

  @protected
  void sse_encode_voting_type(VotingType self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_groupchat_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_groupchat_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_groupchat_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_groupchat_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachment =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAttachmentPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_groupchat_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_groupchat_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDb =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDbPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
