// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Api>>
abstract class Api implements RustOpaqueInterface {
  Future<List<Member>> addMembers({
    required String groupId,
    required List<User> users,
  });

  Future<(Event, Message)> createEvent({
    required String groupId,
    required Event event,
  });

  Future<(Poll, Message)> createPoll({
    required String groupId,
    required Poll poll,
  });

  Future<bool> deleteMessage({
    required String groupId,
    required String messageId,
  });

  Future<Message> editMessage({
    required String groupId,
    required String messageId,
    required String text,
  });

  Future<List<Chat>> getChats({
    required PlatformInt64 page,
    required PlatformInt64 pageSize,
  });

  Future<Event> getEvent({required String groupId, required String eventId});

  Future<List<Event>> getEvents({required String groupId});

  Future<Group> getGroup({required String groupId});

  Future<List<Group>> getGroups({
    required PlatformInt64 page,
    required PlatformInt64 pageSize,
  });

  Future<Me> getMe();

  Future<List<Member>> getMembers({required String groupId});

  Future<List<Message>> getMessages({
    required String groupId,
    required PlatformInt64 limit,
    String? beforeId,
    String? afterId,
    String? sinceId,
  });

  Future<Poll> getPoll({required String groupId, required String pollId});

  Future<List<Poll>> getPolls({required String groupId});

  Future<User> getUser({required String userId});

  static Future<Api> init({required String token}) =>
      RustLib.instance.api.crateApiChatApiApiInit(token: token);

  Future<List<Reaction>> likeMessage({
    required String groupId,
    required String messageId,
    required String unicode,
  });

  Future<bool> pinMessage({required String groupId, required String messageId});

  Future<bool> removeMember({
    required String groupId,
    required String memberId,
  });

  Future<Message> sendMessage({required Message message});

  Future<List<Reaction>> unlikeMessage({
    required String groupId,
    required String messageId,
  });

  Future<bool> unpinMessage({
    required String groupId,
    required String messageId,
  });

  Future<Me> updateMe({required Me me});

  Future<Attachment> uploadFile({
    required String groupId,
    required String filename,
    required List<int> file,
  });

  Future<Attachment> uploadImage({required List<int> image});

  Future<Poll> votePoll({
    required String groupId,
    required String pollId,
    required VotingType votingType,
    required List<String> votes,
  });
}
