// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `add_members`, `create_event`, `create_group`, `create_poll`, `delete_group`, `delete_message`, `edit_message`, `get_chats`, `get_event`, `get_events`, `get_group`, `get_groups`, `get_me`, `get_members`, `get_messages`, `get_poll`, `get_polls`, `get_user`, `join_group`, `like_message`, `new`, `pin_message`, `rejoin_group`, `remove_member`, `send_message`, `unlike_message`, `unpin_message`, `update_me`, `upload_file`, `upload_image`, `vote_poll`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Api>>
abstract class Api implements RustOpaqueInterface {}
