// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Db>>
abstract class Db implements RustOpaqueInterface {
  Future<List<Chat>> getChats();

  Future<void> getEvent({required String id});

  Future<List<Group>> getGroups();

  Future<Me?> getMe();

  Future<List<Member>> getMembers({required List<String> ids});

  Future<List<Message>> getMessages({required List<String> ids});

  Future<void> getPoll({required String id});

  Future<User?> getUser({required String id});

  Future<List<User>> getUsers({required String search});

  static Future<Db> open({required String folder}) =>
      RustLib.instance.api.crateApiDatabaseDbOpen(folder: folder);

  Future<void> saveChats({required List<Chat> chats});

  Future<void> saveEvent({required Event event});

  Future<void> saveGroups({required List<Group> groups});

  Future<void> saveMe({required Me me});

  Future<void> saveMembers({required List<Member> members});

  Future<void> saveMessages({required List<Message> messages});

  Future<void> savePoll({required Poll poll});

  Future<void> saveUsers({required List<User> users});
}
