// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `compact`, `get_chats`, `get_event`, `get_groups`, `get_me`, `get_members`, `get_messages`, `get_poll`, `get_user`, `get_users`, `open`, `save_chats`, `save_event`, `save_groups`, `save_me`, `save_members`, `save_messages`, `save_poll`, `save_users`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Db>>
abstract class Db implements RustOpaqueInterface {}
