// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `member_roles`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DbItem`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `bytes_decode`, `bytes_encode`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`

Future<String> emptyUnicode() =>
    RustLib.instance.api.crateApiTypesEmptyUnicode();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Attachment>>
abstract class Attachment implements RustOpaqueInterface {}

class Chat {
  final String id;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final String otherUserId;
  final PlatformInt64 messagesCount;
  final String? lastMessageId;

  const Chat({
    required this.id,
    required this.createdAt,
    required this.updatedAt,
    required this.otherUserId,
    required this.messagesCount,
    this.lastMessageId,
  });

  static Future<Chat> default_() =>
      RustLib.instance.api.crateApiTypesChatDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      otherUserId.hashCode ^
      messagesCount.hashCode ^
      lastMessageId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Chat &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          otherUserId == other.otherUserId &&
          messagesCount == other.messagesCount &&
          lastMessageId == other.lastMessageId;
}

class ChatError implements FrbException {
  final String message;
  final String? data;

  const ChatError({required this.message, this.data});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ChatError> newInstance({
    required String message,
    required String data,
  }) => RustLib.instance.api.crateApiTypesChatErrorNew(
    message: message,
    data: data,
  );

  @override
  int get hashCode => message.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatError &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          data == other.data;
}

class Event {
  final String id;
  final String groupId;
  final String creatorId;
  final String name;
  final String description;
  final EventLocation? location;
  final String startAt;
  final String endAt;
  final bool isAllDay;
  final String timezone;
  final Int32List reminders;
  final List<String> going;
  final List<String> notGoing;
  final String createdAt;
  final String updatedAt;
  final String shareUrl;
  final String shareQrCode;

  const Event({
    required this.id,
    required this.groupId,
    required this.creatorId,
    required this.name,
    required this.description,
    this.location,
    required this.startAt,
    required this.endAt,
    required this.isAllDay,
    required this.timezone,
    required this.reminders,
    required this.going,
    required this.notGoing,
    required this.createdAt,
    required this.updatedAt,
    required this.shareUrl,
    required this.shareQrCode,
  });

  static Future<Event> default_() =>
      RustLib.instance.api.crateApiTypesEventDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Event> newInstance({
    required String name,
    required String description,
    required String startAt,
    required String endAt,
    required String timezone,
    required bool isAllDay,
    EventLocation? location,
    required List<int> reminders,
  }) => RustLib.instance.api.crateApiTypesEventNew(
    name: name,
    description: description,
    startAt: startAt,
    endAt: endAt,
    timezone: timezone,
    isAllDay: isAllDay,
    location: location,
    reminders: reminders,
  );

  @override
  int get hashCode =>
      id.hashCode ^
      groupId.hashCode ^
      creatorId.hashCode ^
      name.hashCode ^
      description.hashCode ^
      location.hashCode ^
      startAt.hashCode ^
      endAt.hashCode ^
      isAllDay.hashCode ^
      timezone.hashCode ^
      reminders.hashCode ^
      going.hashCode ^
      notGoing.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      shareUrl.hashCode ^
      shareQrCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Event &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          groupId == other.groupId &&
          creatorId == other.creatorId &&
          name == other.name &&
          description == other.description &&
          location == other.location &&
          startAt == other.startAt &&
          endAt == other.endAt &&
          isAllDay == other.isAllDay &&
          timezone == other.timezone &&
          reminders == other.reminders &&
          going == other.going &&
          notGoing == other.notGoing &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          shareUrl == other.shareUrl &&
          shareQrCode == other.shareQrCode;
}

class EventLocation {
  final String name;
  final String address;
  final double lat;
  final double lng;

  const EventLocation({
    required this.name,
    required this.address,
    required this.lat,
    required this.lng,
  });

  static Future<EventLocation> default_() =>
      RustLib.instance.api.crateApiTypesEventLocationDefault();

  @override
  int get hashCode =>
      name.hashCode ^ address.hashCode ^ lat.hashCode ^ lng.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventLocation &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          address == other.address &&
          lat == other.lat &&
          lng == other.lng;
}

class Group {
  final String id;
  final String name;
  final String groupType;
  final String? description;
  final String? imageUrl;
  final String creatorUserId;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64 messagesCount;
  final String? lastMessageId;
  final PlatformInt64 lastMessageCreatedAt;
  final PlatformInt64 lastMessageUpdatedAt;
  final String? themeName;
  final bool requiresApproval;
  final bool showJoinQuestion;
  final String? theJoinQuestion;
  final List<String> messageDeletionMode;
  final String? shareUrl;
  final String? shareQrCodeUrl;
  final bool membersSaved;
  final bool messagesSaved;

  const Group({
    required this.id,
    required this.name,
    required this.groupType,
    this.description,
    this.imageUrl,
    required this.creatorUserId,
    required this.createdAt,
    required this.updatedAt,
    required this.messagesCount,
    this.lastMessageId,
    required this.lastMessageCreatedAt,
    required this.lastMessageUpdatedAt,
    this.themeName,
    required this.requiresApproval,
    required this.showJoinQuestion,
    this.theJoinQuestion,
    required this.messageDeletionMode,
    this.shareUrl,
    this.shareQrCodeUrl,
    required this.membersSaved,
    required this.messagesSaved,
  });

  static Future<Group> default_() =>
      RustLib.instance.api.crateApiTypesGroupDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      groupType.hashCode ^
      description.hashCode ^
      imageUrl.hashCode ^
      creatorUserId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      messagesCount.hashCode ^
      lastMessageId.hashCode ^
      lastMessageCreatedAt.hashCode ^
      lastMessageUpdatedAt.hashCode ^
      themeName.hashCode ^
      requiresApproval.hashCode ^
      showJoinQuestion.hashCode ^
      theJoinQuestion.hashCode ^
      messageDeletionMode.hashCode ^
      shareUrl.hashCode ^
      shareQrCodeUrl.hashCode ^
      membersSaved.hashCode ^
      messagesSaved.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Group &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          groupType == other.groupType &&
          description == other.description &&
          imageUrl == other.imageUrl &&
          creatorUserId == other.creatorUserId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          messagesCount == other.messagesCount &&
          lastMessageId == other.lastMessageId &&
          lastMessageCreatedAt == other.lastMessageCreatedAt &&
          lastMessageUpdatedAt == other.lastMessageUpdatedAt &&
          themeName == other.themeName &&
          requiresApproval == other.requiresApproval &&
          showJoinQuestion == other.showJoinQuestion &&
          theJoinQuestion == other.theJoinQuestion &&
          messageDeletionMode == other.messageDeletionMode &&
          shareUrl == other.shareUrl &&
          shareQrCodeUrl == other.shareQrCodeUrl &&
          membersSaved == other.membersSaved &&
          messagesSaved == other.messagesSaved;
}

class Me {
  final String id;
  final String name;
  final String? imageUrl;
  final String phoneNumber;
  final String? email;
  final String? bio;
  final String? songUrl;
  final String locale;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final String shareUrl;
  final String shareQrCodeUrl;

  const Me({
    required this.id,
    required this.name,
    this.imageUrl,
    required this.phoneNumber,
    this.email,
    this.bio,
    this.songUrl,
    required this.locale,
    required this.createdAt,
    required this.updatedAt,
    required this.shareUrl,
    required this.shareQrCodeUrl,
  });

  static Future<Me> default_() => RustLib.instance.api.crateApiTypesMeDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      imageUrl.hashCode ^
      phoneNumber.hashCode ^
      email.hashCode ^
      bio.hashCode ^
      songUrl.hashCode ^
      locale.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      shareUrl.hashCode ^
      shareQrCodeUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Me &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          imageUrl == other.imageUrl &&
          phoneNumber == other.phoneNumber &&
          email == other.email &&
          bio == other.bio &&
          songUrl == other.songUrl &&
          locale == other.locale &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          shareUrl == other.shareUrl &&
          shareQrCodeUrl == other.shareQrCodeUrl;
}

class Member {
  final String id;
  final String userId;
  final String groupId;
  final String nickname;
  final List<String> roles;
  final bool muted;
  final bool autokicked;

  const Member({
    required this.id,
    required this.userId,
    required this.groupId,
    required this.nickname,
    required this.roles,
    required this.muted,
    required this.autokicked,
  });

  static Future<Member> default_() =>
      RustLib.instance.api.crateApiTypesMemberDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      groupId.hashCode ^
      nickname.hashCode ^
      roles.hashCode ^
      muted.hashCode ^
      autokicked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Member &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          groupId == other.groupId &&
          nickname == other.nickname &&
          roles == other.roles &&
          muted == other.muted &&
          autokicked == other.autokicked;
}

class Message {
  final String id;
  final String groupId;
  final String senderId;
  final bool system;
  final String? text;
  final List<Reaction> reactions;
  final List<Attachment> attachments;
  final String sourceGuid;
  final PlatformInt64? pinnedAt;
  final PlatformInt64 createdAt;
  final PlatformInt64? updatedAt;
  final bool sending;

  const Message({
    required this.id,
    required this.groupId,
    required this.senderId,
    required this.system,
    this.text,
    required this.reactions,
    required this.attachments,
    required this.sourceGuid,
    this.pinnedAt,
    required this.createdAt,
    this.updatedAt,
    required this.sending,
  });

  static Future<Message> default_() =>
      RustLib.instance.api.crateApiTypesMessageDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Message> newInstance({
    required String groupId,
    required String text,
    List<Attachment>? attachments,
  }) => RustLib.instance.api.crateApiTypesMessageNew(
    groupId: groupId,
    text: text,
    attachments: attachments,
  );

  @override
  int get hashCode =>
      id.hashCode ^
      groupId.hashCode ^
      senderId.hashCode ^
      system.hashCode ^
      text.hashCode ^
      reactions.hashCode ^
      attachments.hashCode ^
      sourceGuid.hashCode ^
      pinnedAt.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      sending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Message &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          groupId == other.groupId &&
          senderId == other.senderId &&
          system == other.system &&
          text == other.text &&
          reactions == other.reactions &&
          attachments == other.attachments &&
          sourceGuid == other.sourceGuid &&
          pinnedAt == other.pinnedAt &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          sending == other.sending;
}

class Poll {
  final String id;
  final String subject;
  final String ownerId;
  final String groupId;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;
  final PlatformInt64 expiration;
  final String status;
  final List<PollOption> options;
  final VotingType votingType;
  final Visibility visibility;
  final List<String> userVotes;

  const Poll({
    required this.id,
    required this.subject,
    required this.ownerId,
    required this.groupId,
    required this.createdAt,
    required this.updatedAt,
    required this.expiration,
    required this.status,
    required this.options,
    required this.votingType,
    required this.visibility,
    required this.userVotes,
  });

  static Future<Poll> default_() =>
      RustLib.instance.api.crateApiTypesPollDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Poll> newInstance({
    required String subject,
    required VotingType votingType,
    required Visibility visibility,
    required List<PollOption> options,
    required PlatformInt64 expiration,
  }) => RustLib.instance.api.crateApiTypesPollNew(
    subject: subject,
    votingType: votingType,
    visibility: visibility,
    options: options,
    expiration: expiration,
  );

  @override
  int get hashCode =>
      id.hashCode ^
      subject.hashCode ^
      ownerId.hashCode ^
      groupId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      expiration.hashCode ^
      status.hashCode ^
      options.hashCode ^
      votingType.hashCode ^
      visibility.hashCode ^
      userVotes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Poll &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          subject == other.subject &&
          ownerId == other.ownerId &&
          groupId == other.groupId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          expiration == other.expiration &&
          status == other.status &&
          options == other.options &&
          votingType == other.votingType &&
          visibility == other.visibility &&
          userVotes == other.userVotes;
}

class PollOption {
  final String id;
  final String title;
  final int votes;
  final List<String>? voterIds;

  const PollOption({
    required this.id,
    required this.title,
    required this.votes,
    this.voterIds,
  });

  static Future<PollOption> default_() =>
      RustLib.instance.api.crateApiTypesPollOptionDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<PollOption> newInstance({
    required int id,
    required String title,
  }) => RustLib.instance.api.crateApiTypesPollOptionNew(id: id, title: title);

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ votes.hashCode ^ voterIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PollOption &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          votes == other.votes &&
          voterIds == other.voterIds;
}

class Reaction {
  final String unicode;
  final List<String> userIds;

  const Reaction({required this.unicode, required this.userIds});

  static Future<Reaction> default_() =>
      RustLib.instance.api.crateApiTypesReactionDefault();

  @override
  int get hashCode => unicode.hashCode ^ userIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Reaction &&
          runtimeType == other.runtimeType &&
          unicode == other.unicode &&
          userIds == other.userIds;
}

class User {
  final String id;
  final String name;
  final String imageUrl;
  final String? bio;
  final String? songUrl;
  final List<String>? photoUrls;
  final List<String> sharedGroups;

  const User({
    required this.id,
    required this.name,
    required this.imageUrl,
    this.bio,
    this.songUrl,
    this.photoUrls,
    required this.sharedGroups,
  });

  static Future<User> default_() =>
      RustLib.instance.api.crateApiTypesUserDefault();

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      imageUrl.hashCode ^
      bio.hashCode ^
      songUrl.hashCode ^
      photoUrls.hashCode ^
      sharedGroups.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is User &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          imageUrl == other.imageUrl &&
          bio == other.bio &&
          songUrl == other.songUrl &&
          photoUrls == other.photoUrls &&
          sharedGroups == other.sharedGroups;
}

enum Visibility {
  anonymous,
  public;

  static Future<Visibility> default_() =>
      RustLib.instance.api.crateApiTypesVisibilityDefault();
}

enum VotingType {
  single,
  multiple;

  static Future<VotingType> default_() =>
      RustLib.instance.api.crateApiTypesVotingTypeDefault();
}
